### ISSUE TITLE
GApp versions do not boot

### ISSUE THREAD

**Issue by thehumanx** [KoysX/treble_alpha_gsi#4]
Both the RO and normal version of GApps build do not boot. 

Also, idk if that's how it is but flashing NikGapps over the vanilla build doesnot install the gapps. 

can you please look into this? Thank you.

@KoysX

**Comment by KoysX** [comment]
I installed NikGapps, NikGapps can be installed and used in vanilla build, you can try to change the version of NikGapps

**Comment by thehumanx** [comment]
can you tell me your flashing process and which one did you flash?

I tried basic version. I tried multiple times but gapps did not show up after booting up.

**Comment by KoysX** [comment]
The steps I installed
1. After brushing into alphadroid, restart the phone
2. Restart to twrp after entering the desktop
3. Brush into NikGapps
4. Restart the phone

NikGapps is using the latest version

**Comment by thehumanx** [comment]
Thanks, man. I will try this method and let you know.

**Comment by thehumanx** [comment]
Turns out my system partition is too low to accommodate the gapps. Thank you for your response.
